# ejb timer properties
TIMER_IDTIMER_NAME=SOGE_TASK
TIMER_IDTIMER_TABLE=WLP_TIMER_S3
TIMER_IDTIMER_DB_SCHEMA=S3_WORKFLOW
TIMER_IDTIMER_BUSY_INTERVAL=5
TIMER_IDTIMER_BASE_INTERVAL=60
TIMER_IDTIMER_WAITING_THRESHOLD=2
TIMER_IDTIMER_MAX_OWNERSHIP=1800

# Timer 2 properties
TIMER2_IDTIMER_NAME=SOGE_TASK_2
TIMER2_IDTIMER_TABLE=WLP_TIMER_S3
TIMER2_IDTIMER_DB_SCHEMA=S3_WORKFLOW
TIMER2_IDTIMER_BUSY_INTERVAL=5
TIMER2_IDTIMER_BASE_INTERVAL=60
TIMER2_IDTIMER_WAITING_THRESHOLD=2
TIMER2_IDTIMER_MAX_OWNERSHIP=1800

# MicroProfile OpenAPI
mp.openapi.scan.disable=false
mp.openapi.scan.packages=it.finanze.siga.rest
# Force standard OpenAPI servers property
mp.openapi.servers=http://localhost:9080/Siga3-batch/api
