 // Source code is unavailable, and was generated by the Fernflower decompiler.
package it.sogei.eaf.util;

import java.io.PrintStream;
import java.io.PrintWriter;

public class CheckException extends Exception {
   private static final long serialVersionUID = -7627162679228891977L;
   private String errorCode;
   private boolean modalError;
   private String ticket;
   private String message;

   public CheckException() {
      this((String)null, "no message", new Throwable(), false);
   }

   public CheckException(String s) {
      this((String)null, s, new Throwable(s), false);
   }

   public CheckException(String s, boolean modalError) {
      this((String)null, s, new Throwable(s), modalError);
   }

   public CheckException(String errorCode, String s) {
      this(errorCode, s, new Throwable(s), false);
   }

   public CheckException(String errorCode, String s, boolean modalError) {
      this(errorCode, s, new Throwable(s), modalError);
   }

   public CheckException(Throwable cause) {
      this((String)null, cause.getMessage(), cause, false);
   }

   public CheckException(Throwable cause, boolean modalError) {
      this((String)null, cause.getMessage(), cause, modalError);
   }

   public CheckException(String message, Throwable cause) {
      this((String)null, message, cause, false);
   }

   public CheckException(String message, Throwable cause, boolean modalError) {
      this((String)null, message, cause, modalError);
   }

   public CheckException(String errorCode, String message, Throwable cause) {
      this(errorCode, message, cause, false);
   }

   public CheckException(String errorCode, String message, Throwable cause, boolean modalError) {
      super(message, cause);
      if (cause instanceof CheckException) {
         this.setTicket(((CheckException)cause).getTicket());
      } else {
         this.setTicket();
      }

      this.errorCode = errorCode;
      this.modalError = modalError;
      this.setMessage(message);
   }

   public void printStackTrace() {
      this.printStackTrace(System.err);
   }

   public void printStackTrace(PrintStream ps) {
      ps.println("CheckException Identificativo errore = " + this.getTicket());
      super.printStackTrace(ps);
   }

   public void printStackTrace(PrintWriter pw) {
      pw.println("CheckException Identificativo errore = " + this.getTicket());
      super.printStackTrace(pw);
   }

   public String getErrorCode() {
      return this.errorCode;
   }

   public void setErrorCode(String errorCode) {
      this.errorCode = errorCode;
   }

   public String getTicket() {
      return this.ticket;
   }

   public void setTicket(String ticket) {
      this.ticket = ticket;
   }

   private void setTicket() {
      this.ticket = "" + System.currentTimeMillis();
   }

   public String getMessage() {
      return this.message == null ? super.getMessage() : this.message;
   }

   public void setMessage(String message) {
      this.message = message;
   }

   public boolean isModalError() {
      return this.modalError;
   }

   public void setModalError(boolean modalError) {
      this.modalError = modalError;
   }
}
