package it.finanze.siga.bean;

import java.io.Serializable;

public class FlagParam extends BaseBean implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -202197940512228878L;
	
	private static String CDR_UTENTE_LOGGATO = null;
	private static String CDR_DI_CUI_E_RESPONSABILE = null;
	private static String CDR_DI_CUI_E_RICHIEDENTE = null;
	private static String CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE = null;
	private static String CDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA = null;
	private static String CDR_DI_CUI_E_RICHIEDENTE_DELEGATO = null;
	private static String CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO = null;
	private static String CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO = null;
	
	
	/** GETTERS AND SETTERS **/
	public static String getCDR_UTENTE_LOGGATO() {
		return CDR_UTENTE_LOGGATO;
	}
	public static void setCDR_UTENTE_LOGGATO(String cDR_UTENTE_LOGGATO) {
		CDR_UTENTE_LOGGATO = cDR_UTENTE_LOGGATO;
	}
	public static String getCDR_DI_CUI_E_RESPONSABILE() {
		return CDR_DI_CUI_E_RESPONSABILE;
	}
	public static void setCDR_DI_CUI_E_RESPONSABILE(String cDR_DI_CUI_E_RESPONSABILE) {
		CDR_DI_CUI_E_RESPONSABILE = cDR_DI_CUI_E_RESPONSABILE;
	}
	public static String getCDR_DI_CUI_E_RICHIEDENTE() {
		return CDR_DI_CUI_E_RICHIEDENTE;
	}
	public static void setCDR_DI_CUI_E_RICHIEDENTE(String cDR_DI_CUI_E_RICHIEDENTE) {
		CDR_DI_CUI_E_RICHIEDENTE = cDR_DI_CUI_E_RICHIEDENTE;
	}
	public static String getCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE() {
		return CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE;
	}
	public static void setCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE(
			String cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE) {
		CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE = cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE;
	}
	public static String getCDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA() {
		return CDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA;
	}
	public static void setCDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA(
			String cDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA) {
		CDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA = cDR_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA;
	}
	public static String getCDR_DI_CUI_E_RICHIEDENTE_DELEGATO() {
		return CDR_DI_CUI_E_RICHIEDENTE_DELEGATO;
	}
	public static void setCDR_DI_CUI_E_RICHIEDENTE_DELEGATO(
			String cDR_DI_CUI_E_RICHIEDENTE_DELEGATO) {
		CDR_DI_CUI_E_RICHIEDENTE_DELEGATO = cDR_DI_CUI_E_RICHIEDENTE_DELEGATO;
	}
	public static String getCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO() {
		return CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO;
	}
	public static void setCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO(
			String cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO) {
		CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO = cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_DELEGATO;
	}
	public static String getCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO() {
		return CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO;
	}
	public static void setCDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO(
			String cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO) {
		CDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO = cDR_DI_OPERATORI_ASSOCIATI_PUNTUALMENTE_IN_VISIBILITA_DELEGATO;
	}

}
