
# ORACLE
cau_url_oracle=java:comp/env/jdbc/OracleSource
cau_db_owner=ess
#cau_db_owner=esscau
siga_url_oracle=java:comp/env/jdbc/OracleSource
siga_db_owner=h_workflow
#siga_db_owner=s3_workflow

### DA COMMENTARE DOPO ####
driver=oracle.jdbc.driver.OracleDriver
url_cau=jdbc:oracle:thin:@oracle-lh.sogei.it:1521:A
#url_cau=jdbc:oracle:thin:@dm03-scan.sogei.it:1521/DM03B
username_cau=ess_read
password_cau=ess_read

#driver=oracle.jdbc.driver.OracleDriver
url_siga=jdbc:oracle:thin:@26.2.163.222:1521:U10A
username_siga=h_workflow
password_siga=h_workflow

#testdriver=oracle.jdbc.driver.OracleDriver
#url_siga=jdbc:oracle:thin:@26.2.63.55:1521:SVU1
#username_siga=s3_workflow
#password_siga=S3_workflow

# LOCALE
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@csa-vl.sogei.it:1521:A
#jdbc.username=ess_read
#jdbc.password=ess_read

# MYSQL
#driver=com.mysql.jdbc.Driver
##server
##url=jdbc:mysql://server-fp:3306/schedemonitoraggio
##url=jdbc:mysql://10.50.51.254:3306/schedemonitoraggio
##locale
#url=jdbc:mysql://localhost:3306/ess
#username=root
#password=root



#driver=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@localhost:1521:ORCL
#username=system
#password=orcl
